const SLOT_X_OFFSET = 4;
const SLOT_Y_OFFSET = 48;
const SLOT_X_SPACE = 32;
const SLOT_Y_SPACE = 40;
const SLOT_WIDTH = 96;
const SLOT_HEIGHT = 28;
const SWITCH_X_OFFSET = SLOT_X_OFFSET + (SLOT_WIDTH + SLOT_X_SPACE) * 4 + 64;
const SWITCH_Y_OFFSET = 32;
const SWITCH_Y_SPACE = 8; // 8;
const SWITCH_SIZE = 128; //50;
const SWITCH_PROPERTY_WIDTH = 160;
const LENS_SIZE = (SWITCH_SIZE + 12) * 2 + SWITCH_Y_SPACE;
const LENS_X_OFFSET = SWITCH_X_OFFSET + SWITCH_SIZE + 32;

export  {
    SLOT_X_OFFSET,
    SLOT_Y_OFFSET,
    SLOT_X_SPACE,
    SLOT_Y_SPACE,
    SLOT_WIDTH,
    SLOT_HEIGHT,
    SWITCH_X_OFFSET,
    SWITCH_Y_OFFSET,
    SWITCH_Y_SPACE,
    SWITCH_SIZE,
    SWITCH_PROPERTY_WIDTH,
    LENS_SIZE,
    LENS_X_OFFSET
}